version: '3.1'

services:
  db:
    image: postgres
    restart: always
    container_name: p6_db
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    container_name: p6_adminer
    ports:
      - 8080:8080
